jobs:
    build:
        docker:
            -image:

dependencies:
    post:
        - pip install -r requirements.txt

test:
    steps:
        - run:
            name: BackendTests
            command: python test.py --junit-xml=coverage.xml --cov=application/ tests/
        - run:
            name: FrontendTests
            command: run test:coveralls

    post:
        - mv coverage.xml $CIRCLE_TEST_REPORTS/reports/coverage.xml
        - cat static/coverage/lcov.info | static/node_modules/coveralls/bin/coveralls.js
        - mv static/junit.xml $CIRCLE_TEST_REPORTS/reports/junit.xml
        - coveralls
