"""empty message

Revision ID: 1c469e280eee
Revises: None
Create Date: 2017-10-23 21:07:25.426575

"""

# revision identifiers, used by Alembic.
revision = '1c469e280eee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
