"""empty message

Revision ID: 2a7cedd5bdb4
Revises: d2db659c43b6
Create Date: 2017-10-02 13:18:05.248975

"""

# revision identifiers, used by Alembic.
revision = '2a7cedd5bdb4'
down_revision = 'd2db659c43b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('waiting_for_discard', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('advanced_cheap_trade', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('left_cheap_trade', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('play_twice', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('right_cheap_trade', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'right_cheap_trade')
    op.drop_column('player', 'play_twice')
    op.drop_column('player', 'left_cheap_trade')
    op.drop_column('player', 'advanced_cheap_trade')
    op.drop_column('game', 'waiting_for_discard')
    # ### end Alembic commands ###
