"""empty message

Revision ID: 68874dfa9e3e
Revises: 884eca1e4ecd
Create Date: 2017-08-08 18:56:50.399971

"""

# revision identifiers, used by Alembic.
revision = '68874dfa9e3e'
down_revision = '884eca1e4ecd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('started', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'started')
    # ### end Alembic commands ###
