"""empty message

Revision ID: 77c4a835af0a
Revises: 2a7cedd5bdb4
Create Date: 2017-10-03 18:43:56.437168

"""

# revision identifiers, used by Alembic.
revision = '77c4a835af0a'
down_revision = '2a7cedd5bdb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardhist', sa.Column('card_colour', sa.String(length=30), nullable=True))
    op.add_column('player', sa.Column('blue', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('brown', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('green', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('grey', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('purple', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('red', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('yellow', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'yellow')
    op.drop_column('player', 'red')
    op.drop_column('player', 'purple')
    op.drop_column('player', 'grey')
    op.drop_column('player', 'green')
    op.drop_column('player', 'brown')
    op.drop_column('player', 'blue')
    op.drop_column('cardhist', 'card_colour')
    # ### end Alembic commands ###
