"""empty message

Revision ID: 87d3b8ec9294
Revises: 22270790f0f2
Create Date: 2017-09-11 19:41:20.686558

"""

# revision identifiers, used by Alembic.
revision = '87d3b8ec9294'
down_revision = '22270790f0f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('cog', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('compass', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('max_wonder', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('tablet', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('wildcard', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'wildcard')
    op.drop_column('player', 'tablet')
    op.drop_column('player', 'max_wonder')
    op.drop_column('player', 'compass')
    op.drop_column('player', 'cog')
    # ### end Alembic commands ###
