"""empty message

Revision ID: 884eca1e4ecd
Revises: None
Create Date: 2017-08-08 18:28:29.710856

"""

# revision identifiers, used by Alembic.
revision = '884eca1e4ecd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'age')
    # ### end Alembic commands ###
