"""empty message

Revision ID: d2db659c43b6
Revises: 87d3b8ec9294
Create Date: 2017-09-19 20:10:32.379445

"""

# revision identifiers, used by Alembic.
revision = 'd2db659c43b6'
down_revision = '87d3b8ec9294'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('military_loss', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'military_loss')
    # ### end Alembic commands ###
