"""empty message

Revision ID: d2db659c43b6
Revises: None
Create Date: 2017-09-19 20:10:32.379445

"""

# revision identifiers, used by Alembic.
revision = 'd2db659c43b6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print('Upgrade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print('Downgrade')
    # ### end Alembic commands ###
