"""empty message

Revision ID: fc22c29ad294
Revises: 77c4a835af0a
Create Date: 2017-10-21 17:50:41.553169

"""

# revision identifiers, used by Alembic.
revision = 'fc22c29ad294'
down_revision = '77c4a835af0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
